name: encuentralo
description: Aplicación de objetos perdidos y encontrados — Universidad Libre

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase — versiones más recientes compatibles entre sí
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # Imágenes — Cloudinary
  image_picker: ^1.1.2
  http: ^1.2.2

  # Utilidades
  url_launcher: ^6.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  min_sdk_android: 21
  remove_alpha_ios: true