// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA19Ix_DSVzQPfTjycss4Z2S6GFwE-tBKs',
    appId: '1:677041950994:web:6538752644301c5c4ea3cb',
    messagingSenderId: '677041950994',
    projectId: 'objetos-perdidos-a976e',
    authDomain: 'objetos-perdidos-a976e.firebaseapp.com',
    storageBucket: 'objetos-perdidos-a976e.firebasestorage.app',
    measurementId: 'G-17DRC7N8G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7NwPhsZJWR1QvsL1q7TpoHfmIODGuwho',
    appId: '1:677041950994:android:7de640695f145ee34ea3cb',
    messagingSenderId: '677041950994',
    projectId: 'objetos-perdidos-a976e',
    storageBucket: 'objetos-perdidos-a976e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADMgziabiTETlnFULuLmAGzBGdHDwMi_o',
    appId: '1:677041950994:ios:08046196645d64054ea3cb',
    messagingSenderId: '677041950994',
    projectId: 'objetos-perdidos-a976e',
    storageBucket: 'objetos-perdidos-a976e.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADMgziabiTETlnFULuLmAGzBGdHDwMi_o',
    appId: '1:677041950994:ios:08046196645d64054ea3cb',
    messagingSenderId: '677041950994',
    projectId: 'objetos-perdidos-a976e',
    storageBucket: 'objetos-perdidos-a976e.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA19Ix_DSVzQPfTjycss4Z2S6GFwE-tBKs',
    appId: '1:677041950994:web:a4948cdef62bac3d4ea3cb',
    messagingSenderId: '677041950994',
    projectId: 'objetos-perdidos-a976e',
    authDomain: 'objetos-perdidos-a976e.firebaseapp.com',
    storageBucket: 'objetos-perdidos-a976e.firebasestorage.app',
    measurementId: 'G-WYP7J0NMZ3',
  );
}
